// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package openapi

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Appointment defines model for Appointment.
type Appointment struct {
	Id        *string    `json:"_id,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	EndTime   *time.Time `json:"endTime,omitempty"`
	Patient   *struct {
		Id      *string  `json:"_id,omitempty"`
		Profile *Profile `json:"profile,omitempty"`
	} `json:"patient,omitempty"`
	Pt *struct {
		Id      *string  `json:"_id,omitempty"`
		Profile *Profile `json:"profile,omitempty"`
	} `json:"pt,omitempty"`
	StartTime *time.Time `json:"startTime,omitempty"`
	Status    *string    `json:"status,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token *string `json:"token,omitempty"`
}

// AvailabilityRequest defines model for AvailabilityRequest.
type AvailabilityRequest struct {
	Slots *[]struct {
		EndTime   *time.Time `json:"endTime,omitempty"`
		StartTime *time.Time `json:"startTime,omitempty"`
	} `json:"slots,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

// Profile defines model for Profile.
type Profile struct {
	Id              *string  `json:"_id,omitempty"`
	Bio             *string  `json:"bio,omitempty"`
	Credentials     *string  `json:"credentials,omitempty"`
	FirstName       *string  `json:"firstName,omitempty"`
	LastName        *string  `json:"lastName,omitempty"`
	Location        *string  `json:"location,omitempty"`
	ProfileImageUrl *string  `json:"profileImageUrl,omitempty"`
	Rating          *float32 `json:"rating,omitempty"`
	Specialty       *string  `json:"specialty,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Role     *string `json:"role,omitempty"`
}

// Reminder defines model for Reminder.
type Reminder struct {
	Id       *string    `json:"_id,omitempty"`
	Message  *string    `json:"message,omitempty"`
	RemindAt *time.Time `json:"remindAt,omitempty"`
}

// Review defines model for Review.
type Review struct {
	Id        *string    `json:"_id,omitempty"`
	Comment   *string    `json:"comment,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Patient   *struct {
		Id      *string  `json:"_id,omitempty"`
		Profile *Profile `json:"profile,omitempty"`
	} `json:"patient,omitempty"`
	Rating    *float32 `json:"rating,omitempty"`
	Therapist *struct {
		Id      *string  `json:"_id,omitempty"`
		Profile *Profile `json:"profile,omitempty"`
	} `json:"therapist,omitempty"`
}

// ReviewRequest defines model for ReviewRequest.
type ReviewRequest struct {
	Comment     *string  `json:"comment,omitempty"`
	Rating      *float32 `json:"rating,omitempty"`
	TherapistId *string  `json:"therapistId,omitempty"`
}

// Therapist defines model for Therapist.
type Therapist struct {
	Id                  *string        `json:"_id,omitempty"`
	AvailableSlots      *[]Appointment `json:"availableSlots,omitempty"`
	AvailableSlotsCount *int           `json:"availableSlotsCount,omitempty"`
	Email               *string        `json:"email,omitempty"`
	Profile             *Profile       `json:"profile,omitempty"`
	Rating              *float32       `json:"rating,omitempty"`
	ReviewCount         *int           `json:"reviewCount,omitempty"`
}

// PutAppointmentsIdStatusJSONBody defines parameters for PutAppointmentsIdStatus.
type PutAppointmentsIdStatusJSONBody struct {
	Status *string `json:"status,omitempty"`
}

// GetTherapistsParams defines parameters for GetTherapists.
type GetTherapistsParams struct {
	Page      *int    `form:"page,omitempty" json:"page,omitempty"`
	Specialty *string `form:"specialty,omitempty" json:"specialty,omitempty"`
}

// PostAppointmentsAvailabilityJSONRequestBody defines body for PostAppointmentsAvailability for application/json ContentType.
type PostAppointmentsAvailabilityJSONRequestBody = AvailabilityRequest

// PutAppointmentsIdStatusJSONRequestBody defines body for PutAppointmentsIdStatus for application/json ContentType.
type PutAppointmentsIdStatusJSONRequestBody PutAppointmentsIdStatusJSONBody

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostProfileJSONRequestBody defines body for PostProfile for application/json ContentType.
type PostProfileJSONRequestBody = Profile

// PostReviewsJSONRequestBody defines body for PostReviews for application/json ContentType.
type PostReviewsJSONRequestBody = ReviewRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create availability (PT only)
	// (POST /appointments/availability)
	PostAppointmentsAvailability(w http.ResponseWriter, r *http.Request)
	// Get a specific PT's available slots
	// (GET /appointments/availability/{ptId})
	GetAppointmentsAvailabilityPtId(w http.ResponseWriter, r *http.Request, ptId string)
	// Get my schedule (PT or patient)
	// (GET /appointments/me)
	GetAppointmentsMe(w http.ResponseWriter, r *http.Request)
	// Book an available appointment
	// (PUT /appointments/{id}/book)
	PutAppointmentsIdBook(w http.ResponseWriter, r *http.Request, id string)
	// Update appointment status (PT)
	// (PUT /appointments/{id}/status)
	PutAppointmentsIdStatus(w http.ResponseWriter, r *http.Request, id string)
	// Login
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
	// Create or update profile
	// (POST /profile)
	PostProfile(w http.ResponseWriter, r *http.Request)
	// Current user's profile
	// (GET /profile/me)
	GetProfileMe(w http.ResponseWriter, r *http.Request)
	// Get my reminders (patient)
	// (GET /reminders/me)
	GetRemindersMe(w http.ResponseWriter, r *http.Request)
	// Create a review
	// (POST /reviews)
	PostReviews(w http.ResponseWriter, r *http.Request)
	// List reviews for therapist
	// (GET /reviews/{therapistId})
	GetReviewsTherapistId(w http.ResponseWriter, r *http.Request, therapistId string)
	// List therapists (with filters)
	// (GET /therapists)
	GetTherapists(w http.ResponseWriter, r *http.Request, params GetTherapistsParams)
	// Get therapist detail
	// (GET /therapists/{id})
	GetTherapistsId(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Create availability (PT only)
// (POST /appointments/availability)
func (_ Unimplemented) PostAppointmentsAvailability(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a specific PT's available slots
// (GET /appointments/availability/{ptId})
func (_ Unimplemented) GetAppointmentsAvailabilityPtId(w http.ResponseWriter, r *http.Request, ptId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get my schedule (PT or patient)
// (GET /appointments/me)
func (_ Unimplemented) GetAppointmentsMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Book an available appointment
// (PUT /appointments/{id}/book)
func (_ Unimplemented) PutAppointmentsIdBook(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update appointment status (PT)
// (PUT /appointments/{id}/status)
func (_ Unimplemented) PutAppointmentsIdStatus(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new user
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create or update profile
// (POST /profile)
func (_ Unimplemented) PostProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Current user's profile
// (GET /profile/me)
func (_ Unimplemented) GetProfileMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get my reminders (patient)
// (GET /reminders/me)
func (_ Unimplemented) GetRemindersMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a review
// (POST /reviews)
func (_ Unimplemented) PostReviews(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List reviews for therapist
// (GET /reviews/{therapistId})
func (_ Unimplemented) GetReviewsTherapistId(w http.ResponseWriter, r *http.Request, therapistId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List therapists (with filters)
// (GET /therapists)
func (_ Unimplemented) GetTherapists(w http.ResponseWriter, r *http.Request, params GetTherapistsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get therapist detail
// (GET /therapists/{id})
func (_ Unimplemented) GetTherapistsId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAppointmentsAvailability operation middleware
func (siw *ServerInterfaceWrapper) PostAppointmentsAvailability(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAppointmentsAvailability(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAppointmentsAvailabilityPtId operation middleware
func (siw *ServerInterfaceWrapper) GetAppointmentsAvailabilityPtId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "ptId" -------------
	var ptId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "ptId", runtime.ParamLocationPath, chi.URLParam(r, "ptId"), &ptId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ptId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppointmentsAvailabilityPtId(w, r, ptId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAppointmentsMe operation middleware
func (siw *ServerInterfaceWrapper) GetAppointmentsMe(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppointmentsMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutAppointmentsIdBook operation middleware
func (siw *ServerInterfaceWrapper) PutAppointmentsIdBook(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAppointmentsIdBook(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutAppointmentsIdStatus operation middleware
func (siw *ServerInterfaceWrapper) PutAppointmentsIdStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAppointmentsIdStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostProfile operation middleware
func (siw *ServerInterfaceWrapper) PostProfile(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetProfileMe operation middleware
func (siw *ServerInterfaceWrapper) GetProfileMe(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfileMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRemindersMe operation middleware
func (siw *ServerInterfaceWrapper) GetRemindersMe(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRemindersMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostReviews operation middleware
func (siw *ServerInterfaceWrapper) PostReviews(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostReviews(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetReviewsTherapistId operation middleware
func (siw *ServerInterfaceWrapper) GetReviewsTherapistId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "therapistId" -------------
	var therapistId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "therapistId", runtime.ParamLocationPath, chi.URLParam(r, "therapistId"), &therapistId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "therapistId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReviewsTherapistId(w, r, therapistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetTherapists operation middleware
func (siw *ServerInterfaceWrapper) GetTherapists(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTherapistsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "specialty" -------------

	err = runtime.BindQueryParameter("form", true, false, "specialty", r.URL.Query(), &params.Specialty)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "specialty", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTherapists(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetTherapistsId operation middleware
func (siw *ServerInterfaceWrapper) GetTherapistsId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTherapistsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/appointments/availability", wrapper.PostAppointmentsAvailability)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/appointments/availability/{ptId}", wrapper.GetAppointmentsAvailabilityPtId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/appointments/me", wrapper.GetAppointmentsMe)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/appointments/{id}/book", wrapper.PutAppointmentsIdBook)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/appointments/{id}/status", wrapper.PutAppointmentsIdStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/profile", wrapper.PostProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/profile/me", wrapper.GetProfileMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/reminders/me", wrapper.GetRemindersMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/reviews", wrapper.PostReviews)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/reviews/{therapistId}", wrapper.GetReviewsTherapistId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/therapists", wrapper.GetTherapists)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/therapists/{id}", wrapper.GetTherapistsId)
	})

	return r
}
