// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Appointment struct {
	ID          uuid.UUID
	SlotID      uuid.NullUUID
	PatientID   uuid.UUID
	TherapistID uuid.UUID
	Status      string
	Notes       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AvailabilitySlot struct {
	ID          uuid.UUID
	TherapistID uuid.UUID
	StartTs     time.Time
	EndTs       time.Time
	Status      string
	Metadata    pqtype.NullRawMessage
	CreatedAt   time.Time
}

type Profile struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	DisplayName  sql.NullString
	Bio          sql.NullString
	Phone        sql.NullString
	Address      pqtype.NullRawMessage
	Specialties  []string
	ProfileExtra pqtype.NullRawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Rating       sql.NullString
}

type Reminder struct {
	ID            uuid.UUID
	AppointmentID uuid.UUID
	ScheduledFor  time.Time
	SentAt        sql.NullTime
	Channel       sql.NullString
	Payload       pqtype.NullRawMessage
	CreatedAt     time.Time
}

type Review struct {
	ID            uuid.UUID
	AppointmentID uuid.UUID
	PatientID     uuid.UUID
	Rating        int32
	Comment       sql.NullString
	CreatedAt     time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
