// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reminders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getUpcomingReminders = `-- name: GetUpcomingReminders :many
SELECT r.id, r.appointment_id, r.scheduled_for, r.payload,
       a.therapist_id, s.start_ts as appointment_start
FROM reminders r
JOIN appointments a ON a.id = r.appointment_id
JOIN availability_slots s ON s.id = a.slot_id
WHERE a.patient_id = $1 AND r.sent_at IS NULL AND r.scheduled_for <= now()
ORDER BY r.scheduled_for ASC
`

type GetUpcomingRemindersRow struct {
	ID               uuid.UUID
	AppointmentID    uuid.UUID
	ScheduledFor     time.Time
	Payload          pqtype.NullRawMessage
	TherapistID      uuid.UUID
	AppointmentStart time.Time
}

// params: patient_id uuid
func (q *Queries) GetUpcomingReminders(ctx context.Context, patientID uuid.UUID) ([]GetUpcomingRemindersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingReminders, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingRemindersRow
	for rows.Next() {
		var i GetUpcomingRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.ScheduledFor,
			&i.Payload,
			&i.TherapistID,
			&i.AppointmentStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingRemindersBefore = `-- name: GetUpcomingRemindersBefore :many
SELECT r.id, r.appointment_id, r.scheduled_for, r.payload,
       a.therapist_id, s.start_ts as appointment_start
FROM reminders r
JOIN appointments a ON a.id = r.appointment_id
JOIN availability_slots s ON s.id = a.slot_id
WHERE a.patient_id = $1 AND r.sent_at IS NULL AND r.scheduled_for <= $2
ORDER BY r.scheduled_for ASC
`

type GetUpcomingRemindersBeforeParams struct {
	PatientID    uuid.UUID
	ScheduledFor time.Time
}

type GetUpcomingRemindersBeforeRow struct {
	ID               uuid.UUID
	AppointmentID    uuid.UUID
	ScheduledFor     time.Time
	Payload          pqtype.NullRawMessage
	TherapistID      uuid.UUID
	AppointmentStart time.Time
}

// params: patient_id uuid, before timestamptz
func (q *Queries) GetUpcomingRemindersBefore(ctx context.Context, arg GetUpcomingRemindersBeforeParams) ([]GetUpcomingRemindersBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingRemindersBefore, arg.PatientID, arg.ScheduledFor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingRemindersBeforeRow
	for rows.Next() {
		var i GetUpcomingRemindersBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.ScheduledFor,
			&i.Payload,
			&i.TherapistID,
			&i.AppointmentStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
